/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        "index": [],
        "pagar": [],
        "storage.local": [
            {
                "name": "path",
                "required": true
            }
        ],
        "storage.local.upload": [
            {
                "name": "path",
                "required": true
            }
        ]
    }
}
export { Ziggy };
